import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { getOutputContent } from '../../services/contentService';

export default function OutputContent() {
  const location = useLocation();
  const navigate = useNavigate();
  const { headline, content, hashtags } = location.state || {
    headline: "Sample Headline",
    content: "Sample content generated by AI.",
    hashtags: "#sample #ai #content"
  };

  // New: Fetch all output contents
  const [allContents, setAllContents] = useState([]);
  useEffect(() => {
    getOutputContent().then(res => {
      if (res.success) setAllContents(res.contents);
    });
  }, []);

  return (
    <div style={{ width: '100%', background: '#f6f8fa', fontFamily: 'Inter, Segoe UI, Arial, sans-serif', minHeight: '100vh', padding: 0 }}>
      <div style={{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'flex-start',
        gap: 32,
        maxWidth: 1200,
        margin: '48px auto',
        width: '100%',
        boxSizing: 'border-box',
      }}>
        {/* Output Card */}
        <div style={{
          flex: '1 1 420px',
          maxWidth: 600,
          minWidth: 320,
          background: '#fff',
          borderRadius: 20,
          boxShadow: '0 6px 32px 0 rgba(44,75,255,0.10), 0 2px 8px rgba(0,0,0,0.08)',
          padding: '40px 36px 32px 36px',
          display: 'flex',
          flexDirection: 'column',
          gap: 28,
          border: '1.5px solid #e0e7ff',
        }}>
          <h2 style={{ fontWeight: 800, fontSize: '1.35rem', color: '#222', marginBottom: 12, letterSpacing: 0.01 }}>AI Content Producer Output</h2>
          {/* Headline Field */}
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 16 }}>
            <div style={{ flex: 1 }}>
              <div style={{ fontWeight: 600, marginBottom: 4, fontSize: '1.08rem' }}>Headline</div>
              <div style={{ background: '#f9fafb', borderRadius: 12, padding: 16, minHeight: 40, fontSize: '1.08rem', color: '#222', border: '1.5px solid #e0e7eb', fontWeight: 500 }}>{headline || '-'}</div>
            </div>
            <button
              style={{
                background: '#f87171',
                color: '#fff',
                border: 'none',
                borderRadius: 10,
                padding: '10px 22px',
                fontWeight: 700,
                fontSize: '1.05rem',
                cursor: 'pointer',
                letterSpacing: 0.5,
                boxShadow: '0 2px 8px #fca5a5',
                transition: 'background 0.18s',
                marginTop: 24
              }}
              onClick={() => alert('Regenerate Headline (implement logic)')}
              onMouseOver={e => e.target.style.background = '#c62828'}
              onMouseOut={e => e.target.style.background = '#f87171'}
            >
              Regenerate
            </button>
          </div>
          {/* Content Field */}
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 16 }}>
            <div style={{ flex: 1 }}>
              <div style={{ fontWeight: 600, marginBottom: 4, fontSize: '1.08rem' }}>Content</div>
              <div style={{ background: '#f9fafb', borderRadius: 12, padding: 16, minHeight: 60, fontSize: '1.08rem', color: '#222', border: '1.5px solid #e0e7eb', fontWeight: 500 }}>{content || '-'}</div>
            </div>
            <button
              style={{
                background: '#f87171',
                color: '#fff',
                border: 'none',
                borderRadius: 10,
                padding: '10px 22px',
                fontWeight: 700,
                fontSize: '1.05rem',
                cursor: 'pointer',
                letterSpacing: 0.5,
                boxShadow: '0 2px 8px #fca5a5',
                transition: 'background 0.18s',
                marginTop: 24
              }}
              onClick={() => alert('Regenerate Content (implement logic)')}
              onMouseOver={e => e.target.style.background = '#c62828'}
              onMouseOut={e => e.target.style.background = '#f87171'}
            >
              Regenerate
            </button>
          </div>
          {/* Hashtags Field */}
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 16 }}>
            <div style={{ flex: 1 }}>
              <div style={{ fontWeight: 600, marginBottom: 4, fontSize: '1.08rem' }}>Hashtags</div>
              <div style={{ background: '#f9fafb', borderRadius: 12, padding: 16, minHeight: 40, fontSize: '1.08rem', color: '#222', border: '1.5px solid #e0e7eb', fontWeight: 500 }}>{hashtags || '-'}</div>
            </div>
            <button
              style={{
                background: '#f87171',
                color: '#fff',
                border: 'none',
                borderRadius: 10,
                padding: '10px 22px',
                fontWeight: 700,
                fontSize: '1.05rem',
                cursor: 'pointer',
                letterSpacing: 0.5,
                boxShadow: '0 2px 8px #fca5a5',
                transition: 'background 0.18s',
                marginTop: 24
              }}
              onClick={() => alert('Regenerate Hashtags (implement logic)')}
              onMouseOver={e => e.target.style.background = '#c62828'}
              onMouseOut={e => e.target.style.background = '#f87171'}
            >
              Regenerate
            </button>
          </div>
          {/* Bottom Buttons */}
          <div style={{ display: 'flex', gap: 16, justifyContent: 'flex-end', marginTop: 32 }}>
            <button
              style={{
                background: '#f87171',
                color: '#fff',
                border: 'none',
                borderRadius: 12,
                padding: '16px 32px',
                fontWeight: 800,
                fontSize: '1.13rem',
                cursor: 'pointer',
                letterSpacing: 0.5,
                boxShadow: '0 2px 8px #fca5a5',
                transition: 'background 0.18s',
              }}
              onClick={() => navigate('/content/create')}
              onMouseOver={e => e.target.style.background = '#c62828'}
              onMouseOut={e => e.target.style.background = '#f87171'}
            >
              Regenerate
            </button>
            <button
              style={{
                background: '#2563eb',
                color: '#fff',
                border: 'none',
                borderRadius: 12,
                padding: '16px 32px',
                fontWeight: 800,
                fontSize: '1.13rem',
                cursor: 'pointer',
                letterSpacing: 0.5,
                boxShadow: '0 2px 8px #a5b4fc',
                transition: 'background 0.18s',
              }}
              onClick={() => alert('Content used! (Implement your logic here)')}
              onMouseOver={e => e.target.style.background = '#1746b3'}
              onMouseOut={e => e.target.style.background = '#2563eb'}
            >
              Use Content
            </button>
          </div>
        </div>
        {/* Analyzer Placeholder */}
        <div style={{
          flex: '0 1 340px',
          minWidth: 260,
          minHeight: 400,
          background: '#f9fafb',
          borderRadius: 18,
          boxShadow: '0 2px 8px rgba(44,75,255,0.06)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: '#bbb',
          fontSize: '1.13rem',
          fontStyle: 'italic',
          marginTop: 0,
          border: '1.5px solid #e0e7ff',
        }}>
          {/* Future Analyzer Components Here */}
          Analyzer space
        </div>
      </div>
      {/* New: List all output contents */}
      <div style={{ maxWidth: 600, margin: '32px auto', background: '#fff', borderRadius: 16, boxShadow: '0 2px 8px #e0e7eb', padding: 24 }}>
        <h3 style={{ fontWeight: 700, fontSize: '1.1rem', marginBottom: 12 }}>All Output Contents (Mocked)</h3>
        <ul style={{ listStyle: 'none', padding: 0 }}>
          {allContents.map(c => (
            <li key={c.id} style={{ marginBottom: 16, borderBottom: '1px solid #eee', paddingBottom: 8 }}>
              <div style={{ fontWeight: 600 }}>{c.title}</div>
              <div style={{ color: '#444', fontSize: '0.98rem' }}>{c.body}</div>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
} 